[package]
name = "sequential"
version = "0.2.0"
edition = "2021"

[features]
serde = ["dep:serde"]

[dependencies]
serde = { version = "1.0", features = ["derive"], optional = true}

[dev-dependencies]
serde_json = "*"
